### PR TITLE
Library project is done.

### PR DESCRIPTION
**Pull request by RaminMammadzada**
In the project we finished the following steps:

- Milestone 1 - Basic initial setups and linter configurations.
- Milestone 2 - Set the project with skeleton HTML/CSS and JS files.
- Milestone 3 - Add a function to the script that can take the user’s input and store the new book objects into an array.
- Milestone 4 - Write a function that loops through the array and displays each book on the page
- Milestone 5 - Add a “NEW BOOK” button that brings up a form allowing users to input the details for the new book
- Milestone 6 - Add a button on each book’s display to remove the book from the library
- Milestone 7 - Add a button on each book’s display to change its read status

### CODE REVIEW

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### **STATUS: INVALID PULL REQUEST. 💢**

Reason:
- The last commit wasn't linted. Please check and make a new commit.

Contact me on slack(@michgolden) for further clarifications if needed.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team
### You have done well so far :clap: However, you have a few issues to fix:-
- [x] We recommend the use of es6 arrow functions to implement your codebase, see below
```
const createIsRead = (cell3, currentBook) =? {
  # code
}
```
- [x] It has data persistence by saving, retrieving, and updating the library books using the localstorage API
- [x] Add all the linting files, install all the required dependencies, configure them well and run the commands, if errors kindly solve them. [Follow this guide](https://github.com/microverseinc/linters-config/tree/master/javascript)
- [x] Upon saving data, clear the fields for the next entry
- [x] the form used to create a book should have validations, you should not be able to create an empty book
### Make the changes and submit the project. Good luck with the next one.
- Happy coding!

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team
### You have done well so far :clap: But you did not finish all the requested changes from the previous review. They are:-
- [x]  It has data persistence by saving, retrieving, and updating the library books using the localstorage API
- [x] Add all the linting files, install all the required dependencies, configure them well and run the commands, if errors kindly solve them. [Follow this guide](https://github.com/microverseinc/linters-config/tree/master/javascript)
### Make the changes and submit for another code review. Good luck!
- Happy coding!

**Review by rOluochKe — APPROVED** [review]
### You got it right. The project has been approved. Congratulations :boom:  :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!
### [Improvements]
- For validation, it's nice if you validate each and every field rather than a pop up for all the fields

**Pull request merged**
